projects:
  beerpenalty-bp:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: eu-central-1
        apiId: yehfw33p3bhofbyhowlbedws6e
        maxDepth: 2
extensions:
  amplify:
    version: 3
